### ISSUE TITLE
3.0 relations problems

### ISSUE THREAD

**Issue by Hesesses** [flugger/laravel-responder#108] opened 2018-02-04 13:18 UTC
I have relations like this:
`set -> todos -> todoUser -> details`

My api call is:
`/sets?with=todos.todoUser`
And I would like to get:
`sets[] -> todos[] -> todouser{} -> details{}`

SetTransformer
`protected $relations = ['todos'];`
TodoTransformer
`protected $relations = ['todoUser'];`
UserTransformer
`protected $load = ['details'];`

Result: **todos are not included**

Changing SetTransformer
`protected $relations = ['todos' => TodoTransformer::class];`

Result: todos are included, todoUser is included, **details not included**

If I change the api call to:
`/sets?with=todos.todoUser.details`

Result: **todos are not included**

To get details relation included I need to change:
TodoTransformer
`protected $relations = ['todoUser' => UserTransformer::class];`

UserTransformer add
`protected $relations = ['details'];`

api call:
`/sets?with=todos.todoUser.details`

Every other combination is not working.

When using v2 this api call `/sets?with=todos.todoUser` was working fine and autoloaded details relation automatically. Am i doing something wrong or why this is happening?

**Comment by flugger** [comment] 2018-02-04 17:20
Ahh, this is indeed unexpected behavior. Managed to replicate in a new project. The problem is, it tries to resolve all `$load` relations recursively by itself without taking account of transformers that are nested through the `$relations` mappings.

I've written a failing test, so will get on to finding a solution as soon as possible!

**Comment by Hesesses** [comment] 2018-02-06 10:30
Sounds good! 😊👍

**Comment by flugger** [comment] 2018-02-06 15:16
This should now be fixed with the latest release. Let me know if you still have issues :)

**Closed by flugger** 2018-02-06 15:16 UTC

**Comment by Hesesses** [comment] 2018-02-08 20:49
I cant get the todoUser relation included anymore after updating to 3.0.2

**Comment by flugger** [comment] 2018-02-08 21:24
Have you added a transformer mapping to all $relations?

**Comment by Hesesses** [comment] 2018-02-08 21:37
I have tried both, with mappings and strings only

**Comment by flugger** [comment] 2018-02-08 21:50
Strange, I can't seem to replicate. Do you have some more information I can work with?

**Comment by flugger** [comment] 2018-02-08 21:55
You can also try to add a dump to `Flugg\Responder\TransformBuilder` to debug this. For instance, what is the output if you add the given line to line 262:

```php
if ($transformer instanceof Transformer) {
            $relations = $transformer->relations($this->with);
            $defaultRelations = $this->removeExcludedRelations($transformer->defaultRelations($this->with));
            $this->with = array_merge($relations, $defaultRelations);
            dd($relations, $defaultRelations);
}
```

**Comment by Hesesses** [comment] 2018-02-08 22:02
`array:1 [
  "todos" => null
]`
I can send you more info on slack if you want?

**Comment by flugger** [comment] 2018-02-08 22:11
Yeah, sure thing!
